### ISSUE TITLE
playscrummy.com no longer available

### ISSUE THREAD

**Issue by deltamualpha** [tsmith512/scrummy#39]
Although this isn't exactly an issue with this _repo_, the hosted version, playscrummy.com, appears to be a casualty of the nodejitsu.com / GoDaddy shutdown. Any plans to migrate?

**Comment by bronislav** [comment]
https://scrummy.herokuapp.com/ ?

**Comment by bronislav** [comment]
It's available now. http://www.playscrummy.com/

**Comment by KCarlile** [comment]
> It's available now. http://www.playscrummy.com/

Not anymore. :( We were previously using it at <http://scrummy.herokuapp.com/>, but that's gone now, too.

**Comment by tsmith512** [comment]
I just relaunched it on https://scrummy.cards if you're still looking! It's a full rewrite in the last few days and it is a little buggy, but I had a team using it this morning. I'd love to see more folks start to use the new one!
